# Generated by Django 6.0.6 on 2026-07-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_about_options_alter_about_about_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about_body',
            new_name='about_description',
        ),
    ]
